---
title: "CookCounty_Property_Prediction_Project"
author: "Jimmy CHEN, Zien Zhu, Lida Wei"
date: "2024-11-25"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = F, tidy = F)
```

```{r}
library(olsrr)
library(readr)
library(tidyverse)
library(dplyr)
library(corrplot)
library(caret)  
library(glmnet)
library(neuralnet)
library(e1071)
library(randomForest)
library(doParallel)
library(ranger)
options(scipen = 999)
```

```{r}
his_data <- read_csv("historic_property_data.csv")
```


```{r}
dim(his_data)
```

```{r}
data_filtered <- his_data[, colMeans(is.na(his_data)) <= 0.1]

# Calculate the number of NA values in each column
na_counts <- colSums(is.na(data_filtered))

# Convert to a data frame for better readability
na_count_df <- data.frame(Column = names(na_counts), NA_Count = na_counts)
print(na_count_df)

# drop NA
data_filtered <- na.omit(data_filtered)
data_filtered
```

```{r}
data_filtered <- data.frame(lapply(data_filtered, function(x) {
  if (is.character(x)) {
    return(as.factor(x))  # Convert character columns to factors
  }else if(is.logical(x)){
    return(as.numeric(x))
  }else {
    return(x)  # Leave numeric columns as is
  }
}))

data_filtered <- data_filtered %>% 
  mutate(geo_ohare_noise = as.factor(geo_ohare_noise),
         geo_floodplain = as.factor(geo_floodplain),
         geo_withinmr100 = as.factor(geo_withinmr100),
         geo_withinmr101300 = as.factor(geo_withinmr101300),
         meta_town_code = as.factor(meta_town_code),
         meta_class = as.factor(meta_class),
         meta_nbhd = as.factor(meta_nbhd),
         char_ext_wall = as.factor(char_ext_wall),
         char_roof_cnst = as.factor(char_roof_cnst),
         char_bsmt = as.factor(char_bsmt),
         char_bsmt_fin = as.factor(char_bsmt_fin),
         char_heat = as.factor(char_heat),
         char_oheat = as.factor(char_oheat),
         char_air = as.factor(char_air),
         char_attic_type = as.factor(char_attic_type),
         char_cnst_qlty = as.factor(char_cnst_qlty),
         char_site = as.factor(char_site),
         char_gar1_size = as.factor(char_gar1_size),
         char_repair_cnd = as.factor(char_repair_cnd),
         char_use = as.factor(char_use),
         char_type_resd = as.factor(char_type_resd)
         )
```

1. linear regression

```{r}
data_filtered_line <- data_filtered %>% select(-meta_class, -geo_property_city, -meta_nbhd, -geo_fips, -geo_school_elem_district, -char_site, -char_cnst_qlty,-meta_town_code, -char_ot_impr,-geo_municipality, -geo_school_hs_district, -geo_property_zip)

# Calculate correlation matrix
corr_test <- data_filtered_line %>%
  select_if(is.numeric)

# Exclude the response variable (assuming it's in the first column)
cor_matrix <- cor(corr_test[, -1])  

# Visualize correlations
corrplot(cor_matrix, method = "color", order = "hclust", tl.cex = 0.7)

# Identify highly correlated pairs (example threshold of 0.6)
high_corr <- findCorrelation(cor_matrix, cutoff = 0.7)

# Remove highly correlated variables
df_high <- cor_matrix[, high_corr] 
list_ded <- colnames(df_high)
```

```{r}
#save the variables that are not highly correlated to a new dataframe
data_filtered_line <- data_filtered_line[, !(names(data_filtered_line) %in% list_ded)]
```

```{r}
set.seed(1)
train.index <- sample(c(1:dim(data_filtered_line)[1]), 0.7*dim(data_filtered_line)[1]) 
head(train.index)
```

```{r}
# training set
train.df <- data_filtered_line[train.index, ]
head(train.df)
```

```{r}
#test set
test.df <- data_filtered_line[-train.index, ]
head(test.df)
```
```{r}
#Variable Selection Using forward Stepwise
model <- lm(sale_price ~., data = train.df)
stepwise_result <- ols_step_forward_p(model)

```

```{r}
# Find the index of the minimum RMSE (Root Mean Squared Error) value in the metrics data frame
which.min(stepwise_result$metrics$rmse)
# Display the metrics data frame to examine all RMSE values and associated information
stepwise_result$metrics

```
```{r}

# List of variables extracted from forwardstepwise variable selection
variables_to_filter <- c("sale_price",
  "meta_certified_est_bldg", "meta_certified_est_land", "meta_deed_type", 
  "char_hd_sf", "geo_black_perc", "geo_other_perc", "char_frpl", 
  "char_bsmt_fin", "char_beds", "char_use", "geo_tract_pop", 
  "geo_asian_perc", "geo_his_perc", "char_type_resd", "ind_large_home", 
  "econ_tax_rate", "char_bsmt", "geo_floodplain", "char_air", 
  "geo_withinmr100", "char_ext_wall", "char_roof_cnst", "char_attic_type", 
  "geo_withinmr101300", "geo_fs_flood_factor", "ind_arms_length", 
  "char_repair_cnd", "char_hbath", "char_gar1_size", "geo_ohare_noise"
)

# Filter the columns in the dataframe
train_forward <- train.df[, variables_to_filter]
test_forward <- test.df[, variables_to_filter]

#regress sale price on all other variables after filter
lm_model <- lm(sale_price ~., data = train_forward)

summary(lm_model)

```


```{r}
# Predict the house prices in the test set using the trained linear regression model (lm_model)
test_forward$predict <- predict(lm_model, newdata = test_forward, type = "response")

# Calculate the Mean Squared Error (MSE) between the actual and predicted house prices in the test set
mean((test_forward$sale_price - test_forward$predict)^2)

```


2. Lasso Regression
```{r}
#Variable Selection Using Lasso Regression
f <- formula(sale_price ~ ., data = train.df) # exclude the intercept
y <- train.df$sale_price # set y as the vector
x <- model.matrix(f, data = train.df) # set x as matrix to fix the lasso model
mylasso <- cv.glmnet(x=x,y=y) # estimate lasso model
lambda.best <- mylasso$lambda.min # optimal λ value (smallest CV MSE) 
coef(mylasso, s = lambda.best) # coefficients corresponding to λ = #

```


```{r}
#filter out variables punished in lasso
train.df <- train.df %>% select(-ind_garage)
test.df <- test.df %>% select(-ind_garage)
model2 <- lm(sale_price ~ ., data = train.df)

```

```{r}
summary(model2)
```

```{r}
test.df$pred <- predict(model2, newdata = test.df, type = "response")
```

```{r}
test_mse <- mean((test.df$sale_price-test.df$pred)^2)
test_mse
```


3. Random Forest

```{r}

# Remove these variables as they are considered less important for predicting house prices based on experience
data_filtered_rf <- data_filtered %>%
  select(-meta_deed_type, 
         -geo_property_city, 
         -geo_property_zip, 
         -geo_fips, 
         -geo_municipality, 
         -geo_school_elem_district, 
         -geo_school_hs_district,
         -meta_town_code,
         -meta_nbhd,
         -ind_arms_length,
         -meta_class,
         -char_cnst_qlty) # Remove ind_arms_length, which means trading method, and 'False' values are only 0.01 percent of all.

str(data_filtered_rf)
```



```{r}
# Set seed for reproducibility
set.seed(123)

# Split data into training (70%) and test (30%) sets
train_index <- createDataPartition(data_filtered_rf$sale_price
, p = 0.7, list = FALSE)
train_data <- data_filtered_rf[train_index, ]
test_data <- data_filtered_rf[-train_index, ]

```

```{r}
# Use simple RF to first get the importance feature graph of all factors in order to choose few vital factors

# Train a Random Forest model with ranger
rf_model_ranger <- ranger(sale_price ~ ., data = train_data, importance = 'impurity', num.trees = 150, mtry = 6)

# View feature importance
print(sort(rf_model_ranger$variable.importance, decreasing = TRUE))

# Visualize feature importance
barplot(sort(rf_model_ranger$variable.importance, decreasing = TRUE), 
        main = "Variable Importance", 
        col = "lightblue", 
        las = 1,                # Rotate axis labels for better readability
        horiz = TRUE,           # Horizontal bars for better variable name alignment
        cex.names = 0.4,        # Adjust the size of the variable names
        xlim = c(0, max(sort(rf_model_ranger$variable.importance, decreasing = TRUE)) * 1.1),  # Adjust x-axis limit for better spacing
        cex.axis = 0.2,         # Adjust size of axis numbers
        cex.main = 0.8)         # Increase title size for better readability
```


```{r}
# see the MSE of the 'original' RF model

# Predict on test data
predictions <- predict(rf_model_ranger, test_data)$predictions

# Calculate MSE
mse <- mean((test_data$sale_price - predictions)^2)

# Print the MSE
print(paste("Mean Squared Error (MSE) on Test Data: ", mse))

```


```{r}
# Create a new dataframe named data_filtered2 with the selected 32 most important variables

# List of selected variables
selected_variables <- c(
  "meta_certified_est_bldg", "meta_certified_est_land",
  "char_bldg_sf", "econ_midincome", 
  "geo_white_perc", "char_fbath", 
  "char_age", "geo_asian_perc", 
  "geo_black_perc", "econ_tax_rate", 
  "char_frpl", "char_rooms", 
  "char_hd_sf", "ind_large_home", 
  "geo_his_perc", "char_beds", 
  "geo_tract_pop", "geo_other_perc", 
  "char_roof_cnst", "char_type_resd", 
  "char_hbath", "char_air", 
  "char_bsmt_fin", "char_gar1_size", 
  "char_ext_wall", "char_use",
  "geo_fs_flood_factor", "char_use",
  "char_attic_type", "char_heat",
  "char_ot_impr", "char_repair_cnd"
)

# Add the target variable 'sale_price' to ensure it is included
selected_variables <- c(selected_variables, "sale_price")

# Select the variables from data_filtered and save to data_filtered2
data_filtered2 <- data_filtered_rf %>% select(all_of(selected_variables))

# View the structure of the new dataframe
str(data_filtered2)

```

```{r}
# use the 32 important variable to train the RF again to get a new one 

# Set seed for reproducibility
set.seed(123)

# Split data into training (70%) and test (30%) sets
train_index <- createDataPartition(data_filtered2$sale_price
, p = 0.7, list = FALSE)
train_data <- data_filtered2[train_index, ]
test_data <- data_filtered2[-train_index, ]
```

```{r}
# Train a Random Forest model with ranger
rf_model_ranger <- ranger(sale_price ~ ., data = train_data, importance = 'impurity', num.trees = 500, mtry = 5)

# Predict on test data
predictions <- predict(rf_model_ranger, test_data)$predictions

# Calculate MSE
mse <- mean((test_data$sale_price - predictions)^2)

# Print the MSE
print(paste("Mean Squared Error (MSE) on Test Data: ", mse))
```
```{r}
pre_data <- read_csv("predict_property_data.csv")
col <- names(train_data)
col <- col[col != "sale_price"]
selected_data <- pre_data %>%
  select(all_of(col))
# Make predictions using the ranger model
prediction <- predict(rf_model_ranger, data = selected_data)

# Assign the predictions to the 'pred' column in the selected_data
pre_data$assessed_value <- prediction$predictions
pre_data <- pre_data[, c("pid", "assessed_value")]
write.csv(pre_data, "assessed_value.csv")
```